routes/web.php
<?php

use App\Mail\UserRegistered;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*  Using many middleware for route group

    Route::middleware(['first', 'second'])->group(function () {
        Route::get('/', function () {
            // Uses first & second Middleware
        });

        Route::get('user/profile', function () {
            // Uses first & second Middleware
        });
    }); 
*/

/* Using Prefix for route to do grouping

    Route::prefix('admin')->group(function () {
        Route::get('users', function () {
            // Matches The "/admin/users" URL
        });
    }); 
*/

/* Using Name for route to do grouping
    
    Route::name('admin.')->group(function () {
        Route::get('users', function () {
            // Route assigned name "admin.users"...
        })->name('users');
    });

*/

/* If you want to add all middleware+name+prefix to one group, it’s more readable to put them into an array:
    
    Route::group([
        'name' => 'admin.', 
        'prefix' => 'admin', 
        'middleware' => 'auth'
    ], function () {
        // ...
    }); 
*/

//Auth Routes
Auth::routes();


Route::get('/', function () {
    return redirect("post/newfeeds");
});

//Admin & User group
Route::group([
    'middleware' => 'auth',
], function() {

    //admin group
    Route::group([
        'middleware' => 'role:admin'
    ], function () {

        // URL: /admin/uri
        // Route name: admin.route-name
        Route::group([
            'name' => 'admin.',
            'prefix' => 'admin',
            'namespace' => 'Admin',
        ], function () {
            
            Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    
        });

        // URL: /user/uri
        // Route name: user.route-name
        Route::group([
            'name' => 'user.',
            'prefix' => 'user',
            'namespace' => 'User',
        ], function () {
            
            Route::post('/', 'UserController@store')->name('user.store');
            Route::get('/create', 'UserController@create')->name('user.create');
    
        });
        
        // URL: /role/uri
        // Route name: role.route-name
        Route::group([
            'name' => 'role.',
            'prefix' => 'role',
            'namespace' => 'Admin',
        ], function () {
            
            Route::get("/", "RoleController@index")->name('role.index'); 
            Route::post('/', 'RoleController@store')->name('role.store');
            Route::get('/create', 'RoleController@create')->name('role.create');
        
            Route::delete('/{role}/destroy', 'RoleController@destroy')->name('role.destroy');
            Route::get("/{role}/edit", "RoleController@edit")->name("role.edit");
            Route::patch('/{role}/update', 'RoleController@update')->name('role.update');
        });

    });

    //blogger group (auth users)
    Route::group([
        'name' => 'post.',
        'prefix' => 'post',
        'namespace' => 'Front',
    ], function () {
 
        // URL: /post/uri
        // Route name: post.create
        Route::get("/", "PostController@index")->name('post.index'); 
        Route::post('/', 'PostController@store')->name('post.store');
        Route::get('/create', 'PostController@create')->name('post.create');

        Route::delete('/{post}/destroy', 'PostController@destroy')->name('post.destroy');
        Route::get("/{post}/edit", "PostController@edit")->name("post.edit");
        Route::patch('/{post}/update', 'PostController@update')->name('post.update');

    });

    Route::group([
        'name' => 'user.',
        'prefix' => 'user',
        'namespace' => 'User',
    ], function () {

        //user profile
        Route::get("/{user}", "UserController@show")->name('user.show');

        //Admin and User itself only can edit User Details
        Route::middleware(["can:view,user"])->group(function(){
            Route::get("/{user}/edit", "UserController@edit")->name('user.edit');
            Route::patch("/{user}/update", "UserController@update")->name('user.update');
        });

        //Role Middleware
        Route::middleware(["role:admin"])->group(function(){
            Route::delete('/{user}/destroy', 'UserController@destroy')->name('user.destroy');
        });

    });

});

//Guest group
Route::group([
    'namespace' => 'Front', //folder name 
    ], function () {
        // URL: /post/uri
        // Route name: post.route-name
        //Mail::to('poepoe.dev.1991@gmail.com')->queue(new UserRegistered);

        Route::group([
            'name' => 'post.', //post.newfeeds
            'prefix' => 'post', //post/newfeeds
        ], function () {
            Route::get('/newfeeds', 'PostController@index')->name('post.newfeeds');
            Route::get('/{post}', 'PostController@show')->name('post.show'); 
        }); 
        
        Route::get('about/', 'AboutController@index')->name('about.index');
        Route::get('/overview', 'AboutController@index')->name('about.overview');
        
});

Route::get('/jobs/{jobs}', function($jobs){
    for ($i=0; $i < $jobs ; $i++) { 
        SomeJob::dispatch();
    }
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo("App\User");
    }

    public function getMediaAttribute($value)
    {
        return asset($value);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'user_bio'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany("App\Post");
    }

    public function permissions(){
        return $this->belongsToMany(Permission::class);
    }

    public function roles(){
        return $this->belongsToMany(Role::class);
    }

    /* public function setPasswordAttribute($value)
    {
        $this->password = bcrypt($value);
    } */

    public function getAvatarAttribute($value)
    {
        return asset($value);
    }

    public function userHasRole($role_name)
    {
        foreach($this->roles as $role){
            return Str::lower($role->name) == Str::lower($role_name);
        }

        return false;
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('users.index', ['users'=>$users]);
    }

    public function show(User $user)
    {
        return view('users.profile', ['user' => $user]);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'name' => 'required|min:8|max:255',
            'email'    => 'required|email',
            'avatar' => 'mimes:jpg,jpeg,png,bmp,tiff |max:2048',
            'password' => [
                'required',
                'string',
                'min:6',             // must be at least 10 characters in length
                'regex:/[a-z]/',      // must contain at least one lowercase letter
                'regex:/[A-Z]/',      // must contain at least one uppercase letter
                'regex:/[0-9]/',      // must contain at least one digit
                'regex:/[@$!%*#?&]/', // must contain a special character
            ],
            'password_confirm' => 'required|same:password' //must same with passwrod
        ]);
        
        if ($validator->passes()) {
            $params = $request->all();
            $name = $params['name'];
            $email = $params['email'];
            $user_bio = $params['user_bio'];
            $avatar = '';

            if(request('avatar')){
                $avatar = $request->file('avatar')->store('uploaded_images');
            }

            if(request('password')){
                $password = $params['password'];
            }

            $user = User::create([
                'name' => $name,
                'email' => $email,
                'user_bio' => $user_bio,
                'avatar' => $avatar,
                'password' => $password
            ]);
            
            session()->flash('success', 'Profile created successfully!');

            return redirect()->route('admin.dashboard');
        }
        
        session()->flash('errors', $validator->errors()->all());
        return back();
    }

    public function edit(User $user)
    {
        $this->authorize("update", $user);
        return view('users.edit',['user'=>$user]);
    }

    public function update(User $user, Request $request)
    {
        $this->authorize("update", $user);
        $validator = \Validator::make($request->all(), [
            'name' => 'required|min:8|max:255',
            'email'    => 'required|email',
            'avatar' => 'mimes:jpg,jpeg,png,bmp,tiff |max:2048',
            'password' => [
                'required',
                'string',
                'min:6',             // must be at least 10 characters in length
                'regex:/[a-z]/',      // must contain at least one lowercase letter
                'regex:/[A-Z]/',      // must contain at least one uppercase letter
                'regex:/[0-9]/',      // must contain at least one digit
                'regex:/[@$!%*#?&]/', // must contain a special character
            ],
            'password_confirm' => 'required|same:password' //must same with passwrod
        ]);
        
        if ($validator->passes()) {
            $params = $request->all();
            //dd($params);
            $user->name = $params['name'];
            $user->email = $params['email'];
            $user->user_bio = $params['user_bio'];
            
            if(request('avatar')){
                $user->avatar = $request->file('avatar')->store('uploaded_images');
            }

            if(request('password')){
                $user->password = $params['password'];
            }

            $user->save();
            
            session()->flash('success', 'Profile updated successfully!');

            return redirect()->route('post.index');
        }
        
        session()->flash('errors', $validator->errors()->all());
        return back();
    }

    public function destroy(User $user ,Request $request){

        $this->authorize("delete", $user);

        $user->delete();

        $request->session()->flash('success', 'User deleted successfully!');

        return back();
    }
}

resources/views/users/create.blade.php
@extends('layouts/default')

@section("content")

    <x-document_title>
        Create Profile
    </x-document_title>

    

    @component('components/flash_message')

    @endcomponent

    <div class="container clearfix">
        <x-page_title>
            Crate User Profile
        </x-page_title>
        <div class="" data-alert-type="inline">

            <div class="row shadow bg-light border  justify-content-center">

                <div class="col-xs-3 col-md-3 p-5 dark" style="">
                    <div  class=" clearfix">
                    <img src="{{ asset('images/user-default.png') }}" class="profile-image aligncenter  mt-4" alt="Avatar" style="width:200px; height:200px; max-width: 400px;">

                    </div>
                    
                </div>

                <div class="col-xs-6 col-md-8  p-5">
                    <form class="row mb-0" id="user-form" method="post" action="{{route('user.store')}}"  enctype="multipart/form-data">
                        @csrf
                        <div class="form-process"></div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-name">Name:</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="text" id="user-form-name" name="name" class="form-control required" placeholder="Enter user name">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="post-form-content">Image:</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="file" id="post-form-avatar" name="avatar" multiple class="file file-loading" data-show-preview="false">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-email">Email:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="email" id="user-form-email" name="email" class="form-control required" placeholder="Enter user email">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-user_bio">About Me:</label>
                                </div>
                                <div class="col-sm-10">
                                    <textarea class="required form-control textarea-message" id="user-form-user_bio"  name="user_bio" rows="6" cols="30"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-password">Password:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="password" id="user-form-password" name="password" class="form-control " value="" placeholder="Enter Password">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-password_confirm">Confirm Password:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="password" id="user-form-password_confirm" name="password_confirm" class="form-control " value="" placeholder="Enter Confirm Password">
                                </div>
                            </div>
                        </div>

                        <div class="col-12 d-flex justify-content-end align-items-center">
                            <button type="button" onclick="window.location='{{route('admin.dashboard')}}'" id="user-form-btn-cancel" class="btn btn-secondary">Cancel</button>
                            <button type="submit" id="user-form-btn-create" class="btn btn-success ml-2">Create</button>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>


    <style>
        .form-group > label.error {
            display: block !important;
            text-transform: none;
        }

        .form-group input.valid ~ label.error,
        .form-group input[type="text"] ~ label.error,
        .form-group input[type="textarea"] ~ label.error,
        .form-group select ~ label.error { display: none !important; }

    </style>
    <script>
        function change_avatar(value){
            $("#name").val(value);
        }
    </script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts/default')

@section("content")

    <x-document_title>
        Edit Profile
    </x-document_title>

    

    @component('components/flash_message')

    @endcomponent

    <div class="container clearfix">
        <x-page_title>
            Edit User Profile
        </x-page_title>
        <div class="" data-alert-type="inline">

            <div class="row shadow bg-light border  justify-content-center">

                <div class="col-xs-3 col-md-3 p-5 dark" style="">
                    <div  class=" clearfix">
                    <img src="{{ $user->avatar }}" class="profile-image aligncenter  mt-4" alt="Avatar" style="width:200px; height:200px; max-width: 400px;">

                    </div>
                    
                </div>

                

                <div class="col-xs-6 col-md-8  p-5">
                    <form class="row mb-0" id="user-form" method="post" action="{{route('user.update', $user->id)}}"  enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        <div class="form-process"></div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-name">Name:</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="text" id="user-form-name" name="name" class="form-control required" value="{{ $user->name }}" placeholder="Enter user name">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="post-form-content">Image:</label>
                                </div>
                                <div class="col-sm-10">
                                    <input type="file" id="post-form-avatar" name="avatar" multiple class="file file-loading" data-show-preview="false">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-email">Email:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="email" id="user-form-email" name="email" class="form-control required" value="{{ $user->email }}" placeholder="Enter user email">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-user_bio">About Me:</label>
                                </div>
                                <div class="col-sm-10">
                                    <textarea class="required form-control textarea-message" id="user-form-user_bio"  name="user_bio" rows="6" cols="30">{{ $user->user_bio }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-password">Password:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="password" id="user-form-password" name="password" class="form-control " value="" placeholder="Enter Password">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 form-group">
                            <div class="row">
                                <div class="col-sm-2 col-form-label">
                                    <label for="user-form-password_confirm">Confirm Password:</label>
                                </div>
                                <div class="col-sm-10">
                                <input type="password" id="user-form-password_confirm" name="password_confirm" class="form-control " value="" placeholder="Enter Confirm Password">
                                </div>
                            </div>
                        </div>

                        <div class="col-12 d-flex justify-content-end align-items-center">
                            <button type="button" onclick="window.location='{{route('user.show', $user->id)}}'" id="user-form-btn-cancel" class="btn btn-secondary">Cancel</button>
                            <button type="submit" id="user-form-btn-update" class="btn btn-success ml-2">Update</button>
                        </div>
                    </form>
                </div>

            </div>

        </div>
    </div>


    <style>
        .form-group > label.error {
            display: block !important;
            text-transform: none;
        }

        .form-group input.valid ~ label.error,
        .form-group input[type="text"] ~ label.error,
        .form-group input[type="textarea"] ~ label.error,
        .form-group select ~ label.error { display: none !important; }

    </style>
    <script>
        function change_avatar(value){
            $("#name").val(value);
        }
    </script>
@endsection

resources/views/users/profile.blade.php
@extends('layouts/default')

<x-document_title>
    User Profile
</x-document_title>

@section("content")

    <div class="container clearfix">
        <div class="row clearfix">

            <div class="col-md-9">

                @component('components/flash_message')

                @endcomponent

                <img src="{{$user->avatar}}" class="profile-image alignleft img-circle img-thumbnail my-0" alt="Avatar" style="max-width: 100px;">

                <div class="heading-block border-0">
                    <h3>{{ $user->name }} </h3>
                    @if ( auth()->user()->can('update', $user) )
                        <a href="{{ route('user.edit', $user->id) }}"><span title="Edit Profile" >Edit Profile Details &nbsp; <i class="icon-user-edit" ></i></span></a>  
                    @endif
                </div>

                <div class="clear"></div>

                <div class="row clearfix">

                    <div class="col-lg-12">

                        <div class="tabs tabs-alt clearfix" id="tabs-profile">

                            <ul class="tab-nav clearfix">
                                <li><a href="#tab-posts"> Posts</a></li>
                                <li><a href="#tab-replies"> Followers</a></li>
                                <li><a href="#tab-connections"> Followings</a></li>
                            </ul>

                            <div class="tab-container">

                                <div class="tab-content clearfix" id="tab-posts">

                                    <!-- Posts
                                    ============================================= -->
                                    <div class="row gutter-40 posts-md mt-4">

                                        @foreach ($user->posts as $post)
                                            <x-post_card>
                                                @slot('post_title')
                                                    {{ $post->title }}
                                                @endslot
                                                @slot('post_created_date')
                                                    {{ $post->created_at->diffForHumans() }}
                                                @endslot
                                                @slot('post_media')
                                                    {{ $post->media }}
                                                @endslot
                                                @slot('post_id')
                                                    {{ $post->id }}
                                                @endslot
                                                @slot('editable')
                                                    {{ auth()->user()->can('update', $post)}}
                                                @endslot
                                                @slot('deletable')
                                                    {{ auth()->user()->can('delete', $post)}}
                                                @endslot
                                                {{ $post->content }}

                                            </x-post_card>
                                        @endforeach
                                        

                                    </div>

                                </div>
                                <div class="tab-content clearfix" id="tab-replies">

                                    here will show user's followers

                                </div>
                                <div class="tab-content clearfix" id="tab-connections">

                                    Here will show user following


                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

            <div class="w-100 line d-block d-md-none"></div>

            <div class="col-md-3">

                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Profile</div><i class="icon-user"></i></a>
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Servers</div><i class="icon-laptop2"></i></a>
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Messages</div><i class="icon-envelope2"></i></a>
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Billing</div><i class="icon-credit-cards"></i></a>
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Settings</div><i class="icon-cog"></i></a>
                    <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Logout</div><i class="icon-line2-logout"></i></a>
                </div>

                <div class="fancy-title topmargin title-border">
                    <h4>About Me</h4>
                </div>

                <p>{{ $user->user_bio }}</p>

                <div class="fancy-title topmargin title-border">
                    <h4>Social Profiles</h4>
                </div>

                <a href="#" class="social-icon si-facebook si-small si-rounded si-light" title="Facebook">
                    <i class="icon-facebook"></i>
                    <i class="icon-facebook"></i>
                </a>

                <a href="#" class="social-icon si-gplus si-small si-rounded si-light" title="Google+">
                    <i class="icon-gplus"></i>
                    <i class="icon-gplus"></i>
                </a>

                <a href="#" class="social-icon si-dribbble si-small si-rounded si-light" title="Dribbble">
                    <i class="icon-dribbble"></i>
                    <i class="icon-dribbble"></i>
                </a>

                <a href="#" class="social-icon si-flickr si-small si-rounded si-light" title="Flickr">
                    <i class="icon-flickr"></i>
                    <i class="icon-flickr"></i>
                </a>

                <a href="#" class="social-icon si-linkedin si-small si-rounded si-light" title="LinkedIn">
                    <i class="icon-linkedin"></i>
                    <i class="icon-linkedin"></i>
                </a>

                <a href="#" class="social-icon si-twitter si-small si-rounded si-light" title="Twitter">
                    <i class="icon-twitter"></i>
                    <i class="icon-twitter"></i>
                </a>

            </div>

        </div>
    </div>
    
@endsection